import test from 'node:test';
import assert from 'node:assert/strict';
import {planStatus,postStatus,filterPosts,planProgress,csvExport,connectionStatus} from '../jm_workbench/web/static/community-v2-model.js';

const data={accounts:[{id:'a',enabled:true,platform:'tieba',identity:'same',sync_status:'verified'}],platforms:[{id:'tieba',name:'百度贴吧',automatic:true}],risk:[],plans:[]};
const plan={id:'p',state:'enabled',platform:'tieba',payload:{account_id:'a'},days:[{day:'2026-10-03',counts:{thread:{submitted:1},reply:{submitted:5}}},{day:'2026-10-04',counts:{thread:{submitted:0},reply:{submitted:2}}}]};
test('platform restriction overrides login and enabled plan without changing data',()=>{const d={...data,risk:[{platform:'tieba',reason:'restriction'}]};assert.equal(planStatus(plan,d).key,'blocked');assert.equal(plan.state,'enabled');assert.equal(planStatus(plan,data).key,'enabled')});
test('pending sync is not shown as connected despite historical identity',()=>{assert.equal(connectionStatus({...data.accounts[0],sync_status:'pending'}).key,'login');assert.equal(planStatus(plan,{...data,accounts:[{...data.accounts[0],sync_status:'pending'}]}).key,'login')});
test('today progress does not borrow yesterday totals',()=>{assert.equal(planProgress(plan,'2026-10-04').reply.submitted,2);assert.equal(planProgress(plan,'2026-10-05').reply.submitted,0)});
test('unknown overrides accepted and receipts do not imply visible',()=>{assert.equal(postStatus({state:'active',jobs:[{state:'submitted',receipt:{visibility:'unverified'}},{state:'unknown'}]}).key,'unknown');assert.equal(postStatus({jobs:[{state:'submitted',receipt:{visibility:'unverified'}}]}).key,'submitted');assert.equal(postStatus({jobs:[{state:'recorded',receipt:{url:'https://example.com'}}]}).key,'recorded')});
test('filters match full body source target and selected plan without assuming one target',()=>{const posts=[{id:'p1',plan_id:'plan1',state:'draft',payload:{kind:'reply',title:'note',body:'中文正文',source_title:'原帖问题',targets:[{account_id:'a',destination:'https://example.com/123'}]},jobs:[]},{id:'p2',state:'draft',payload:{kind:'thread',title:'other',targets:[]},jobs:[]}];assert.equal(filterPosts({...data,posts},{q:'原帖问题',kind:'reply',plan:'plan1'}).length,1);assert.equal(filterPosts({...data,posts},{platform:'tieba',q:'中文正文'}).length,1);assert.equal(filterPosts({...data,posts},{plan:'missing'}).length,0)});
test('CSV exports full text and neutralizes formulas including leading whitespace',()=>{const out=csvExport([{id:'one',state:'draft',payload:{title:' =2+2',body:'a,"b"\n下一行',targets:[]},jobs:[]}],data);assert.ok(out.includes("' =2+2"));assert.ok(out.includes('a,""b""\n下一行'))});
